---
# Global SSH Hardening
# Trust on first use, but alert if the key changes. Safer than 'no'.
ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
grafana_client_id: grafana
grafana_client_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38353637616135323562363835343135623238383134343366306664636563663065323534636135
          3866643039316435613564616239383832336535636462660a313265366234323336343438313433
          33363030303831613933306461333931323961663964353435326633643436646236393263643731
          3339396332363830340a356134383162643437643332623737306530356435303337653435333039
          62626366383463353035383237333233376331643262303361343435623965646462656662653636
          6232653062386463363365333461316430633437313137336462
grafana_admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66363336383463613730303161643938336435653361303738386363336537343465663335643839
          3966616435643563363462303330663938373532633662620a353939306162383361633534313438
          34363733656337613964373166653263666231303434386338396264343238313239306130663035
          3435383938306535310a306563343263653866316162333834393134666439363137383530613532
          61666234663065353433653931623030386533353666633138663037323332363861633534633433
          6632383330363534356132396264353836316265313532343130
