---
# Global SSH Hardening
# Trust on first use, but alert if the key changes. Safer than 'no'.
ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
grafana_client_id: grafana
grafana_client_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38353637616135323562363835343135623238383134343366306664636563663065323534636135
          3866643039316435613564616239383832336535636462660a313265366234323336343438313433
          33363030303831613933306461333931323961663964353435326633643436646236393263643731
          3339396332363830340a356134383162643437643332623737306530356435303337653435333039
          62626366383463353035383237333233376331643262303361343435623965646462656662653636
          6232653062386463363365333461316430633437313137336462
grafana_admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66363336383463613730303161643938336435653361303738386363336537343465663335643839
          3966616435643563363462303330663938373532633662620a353939306162383361633534313438
          34363733656337613964373166653263666231303434386338396264343238313239306130663035
          3435383938306535310a306563343263653866316162333834393134666439363137383530613532
          61666234663065353433653931623030386533353666633138663037323332363861633534633433
          6632383330363534356132396264353836316265313532343130

vault_desec_token_proxmox: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34326436663830356537336162363031333938633438363230396631323966363564626565306237
          3462386630643633363832393364616663333365643065320a306536373332313136343838373566
          62323833376565313238353863333363323366626363303438663836613536343939393564393465
          3639393634306437660a346536633535303635303931633032356438396531326634643161313165
          31366332356662336563366136376364663466323335333731396136306132376362

vault_noip_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37383764333830616235336631653434633063343435343537643637636666306664616531303730
          6262663163323965313334383165303534656630323861320a393763313032373662643636663930
          31623533663061313264373634306533393037666134316334366133613138636634656532623666
          3063376439653164610a653439376262663264616239646433363831303961653463336338633461
          6266

vault_noip_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63613636343137396437646435663830343333626561326338653631363935383830653366323538
          6234333234383532373338336536313833626566383032650a386463666332366232633537343236
          61353861626439303836353064313232353532643662633535323530313134646538383538383137
          3431633030333966310a383662643262666461386231346665353462313830636532363561646535
          6330

# Global Access Configuration
ansible_user: root
ansible_ssh_private_key_file: /Users/adam.durham/.ssh/id_ansible
