$ANSIBLE_VAULT;1.1;AES256
35363534636265356162353234373139363264326466323964353066333361646265303365666464
3632633765383361643339663032623436373432613238370a353261303930346338353563333935
35396139316338383763646237383036323138633432653463323061313035633736343865396332
3562323763663935610a383232633033646432323234656565646436336465613436373265613033
37326633343265613062663061623337653332393035316563666563643161386162363839313561
33343535363533303063373339346631326162363433653538383639616662323764356431613966
61383632623330656536386165653462616339316264663834323863626631623262663835616137
62363166333761333265356136356561306161623938326239366235376463396331633266346135
6539
