$ANSIBLE_VAULT;1.1;AES256
66626261653336313232633765333366643732636434346231653037313737623366313364376164
3362333034666361666232353263383931333737386430660a636434613264623264616263636638
61366533636132306330623536393236626331396139373264653636306665636161346464633330
3936653737666262300a313462333832663962303565393662623966333938346139643436346166
36616432333564616139383838643331366137376431653533333163313534356337353063393463
30353133303665366462323834326136626639323162353865613766643932616339656630363236
36653733346634643432383733356131663730333039626663376636303561373661353530663830
62646464623534313961626237313231396435616562636437356135363336373163373535353166
66363638616630373465323130656461656331356164656636623333626531363563363765663364
33633730373339613838383364646562323938623935633338383033356236356163643131393165
62666463623339383837323036333834616330616131353730373166616438656566303732393965
37653538376635323435333735336137353762326238383735613363656134633433353732383237
63353964353332333063613137653631323936303432616466393563653561616637
