---
- name: Install Bind9 and Utils
  ansible.builtin.apt:
    name:
      - bind9
      - bind9-utils
      - bind9-doc
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Fix SSL Directory Permissions
  ansible.builtin.file:
    path: /etc/bind/ssl
    state: directory
    owner: root
    group: bind
    mode: '0750'
    recurse: yes

- name: Configure Named Options
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: '0644'
  notify: Restart Bind9

- name: Configure Named Local (Zones)
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: '0644'
  notify: Restart Bind9

- name: Deploy Zone File for chi.lab.amd-e.com
  ansible.builtin.template:
    src: db.chi.lab.amd-e.com.j2
    dest: /etc/bind/db.chi.lab.amd-e.com
    owner: root
    group: bind
    mode: '0644'
  notify: Restart Bind9

- name: Deploy Zone File for lab.amd-e.com
  ansible.builtin.template:
    src: db.lab.amd-e.com.j2
    dest: /etc/bind/db.lab.amd-e.com
    owner: root
    group: bind
    mode: '0644'
  notify: Restart Bind9

- name: Ensure Bind9 Service is Running
  ansible.builtin.service:
    name: named
    state: started
    enabled: true
