---
- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart WhoAmI
  ansible.builtin.service:
    name: whoami
    state: restarted

- name: Restart ddclient
  ansible.builtin.service:
    name: ddclient
    state: restarted
