- name: Install ddclient
  ansible.builtin.apt:
    name: ddclient
    state: present
    update_cache: true

- name: Configure ddclient
  ansible.builtin.template:
    src: ddclient.conf.j2
    dest: /etc/ddclient.conf
    mode: '0600'
  notify: Restart ddclient

- name: Enable and Start ddclient
  ansible.builtin.service:
    name: ddclient
    state: started
    enabled: true
