---
- name: Update CA Trust
  ansible.builtin.shell: >
    if [ -x "$(command -v update-ca-certificates)" ]; then
      update-ca-certificates
    elif [ -x "$(command -v update-ca-trust)" ]; then
      update-ca-trust
    else
      echo "No CA update command found"
    fi
  changed_when: true
