- name: Provision Tanium Client Containers
  hosts: pve01
  gather_facts: false
  roles:
  roles:
    - role: tanium_client_host
  tags: [provision]

- name: Configure Tanium Clients
  hosts: tanium_clients
  gather_facts: true
  vars_files:
    - group_vars/all/tanium_secrets.yml
  roles:
  roles:
    - role: tanium_client
  tags: [install]
